source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ECExtension_Example', :exclusive => true do
  pod "ECExtension", :path => "../"
end

target 'ECExtension_Tests', :exclusive => true do
  pod "ECExtension", :path => "../"

  
end
